---
- name: add idempotency to create user via command
  become: yes
  hosts: rocky
  vars_prompt:
    - name: username
      prompt: Enter username
      private: false
  tasks:
    - name: check user existence
      ansible.builtin.command: id -u {{ username }}
      register: ucheck
      ignore_errors: yes
    - name: create user
      ansible.builtin.command: useradd {{ username }}
      when: '"no such user" in ucheck.stderr'


